sudo: false

language: haskell
ghc: 7.10

cache:
  directories:
    - $HOME/.stack

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --no-terminal setup
  - stack --no-terminal build --only-snapshot

script:
  - stack --no-terminal test
