sudo: false

cache:
  directories:
    - $HOME/.stack

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.3

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=/opt/ghc/7.10.2/bin:$PATH

install:
  - ./travis_long stack --no-terminal setup
  - ./travis_long stack --no-terminal test --only-snapshot

script:
  - stack --no-terminal test
