#!/bin/bash

# First build an image in which we can build our binary
docker build -t bbcheck:build -f docker/Dockerfile-build docker

# Then compile our binary in the Haskell docker image
docker run -i --volume=`pwd`:/src --volume=$HOME/.stack:/root/.stack bbcheck:build /bin/bash <<-EOF

    set -x
    cd /src

    mkdir -p .dist
    stack build --allow-different-user --jobs=4 --local-bin-path=.dist --test --copy-bins

EOF

# Then build a new image that contains only our binary.
docker build -t danpalmer/bbcheck:latest -f docker/Dockerfile-run .
